/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleHIDTransportSupport.framework/AppleHIDTransportSupport
 */

@interface AHTBootLoader : NSObject {
    unsigned int  _connect;
    AHTDevice * _device;
    unsigned int  _imageTag;
    bool  _needsRestoreUpdate;
    NSString * _personality;
    unsigned int  _service;
    NSString * _type;
}

@property (nonatomic) unsigned int connect;
@property (nonatomic, readonly) AHTDevice *device;
@property (nonatomic, readonly) unsigned int imageTag;
@property (nonatomic, readonly) bool needsRestoreUpdate;
@property (nonatomic, readonly) NSString *personality;
@property (nonatomic) unsigned int service;
@property (nonatomic, readonly) NSString *type;

+ (bool)errorFromKernel:(int)arg1 error:(id*)arg2;
+ (unsigned long long)frameworkToDriverOptions:(unsigned long long)arg1;
+ (id)withDevice:(id)arg1 service:(unsigned int)arg2;
+ (id)withService:(unsigned int)arg1;

- (void).cxx_destruct;
- (void)close;
- (unsigned int)connect;
- (void)dealloc;
- (id)device;
- (unsigned int)imageTag;
- (id)initWithDevice:(id)arg1 service:(unsigned int)arg2;
- (id)initWithService:(unsigned int)arg1;
- (bool)loadImage:(id)arg1 options:(unsigned long long)arg2 error:(id*)arg3;
- (bool)needsRestoreUpdate;
- (bool)open:(id*)arg1;
- (id)personality;
- (bool)reloadProperties:(unsigned long long)arg1 error:(id*)arg2;
- (unsigned int)service;
- (void)setConnect:(unsigned int)arg1;
- (void)setService:(unsigned int)arg1;
- (id)type;
- (bool)updateProperty:(id)arg1 property:(id)arg2 options:(unsigned long long)arg3 error:(id*)arg4;

@end
