/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleHIDTransportSupport.framework/AppleHIDTransportSupport
 */

@interface AHTImageLoader : NSObject {
    AHTBootLoader * _bootloader;
}

@property (nonatomic, readonly) AHTBootLoader *bootloader;

+ (id)withBootLoader:(id)arg1;

- (void).cxx_destruct;
- (id)bootloader;
- (bool)checkIM4PFile:(id)arg1;
- (id)findImageInDirectory:(id)arg1 error:(id*)arg2;
- (id)initWithBootLoader:(id)arg1;
- (bool)loadImageFromFile:(id)arg1 options:(unsigned long long)arg2 error:(id*)arg3;
- (bool)updatePropertyFromFile:(id)arg1 filePath:(id)arg2 options:(unsigned long long)arg3 error:(id*)arg4;

@end
