/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleCVA.framework/AppleCVA
 */

@interface CVAAlphaFilter : CIFilter {
    CIImage * _inputAlpha;
}

@property (retain) CIImage *inputAlpha;

- (void).cxx_destruct;
- (id)customAttributes;
- (id)init;
- (id)inputAlpha;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })outputExtent;
- (id)outputImage;
- (void)setInputAlpha:(id)arg1;

@end
