/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleCVA.framework/AppleCVA
 */

@interface CVACoCFilter : CIFilter {
    NSNumber * _centerShift;
    NSNumber * _deltaShift;
    CIImage * _inputDepth;
}

@property (retain) NSNumber *centerShift;
@property (retain) NSNumber *deltaShift;
@property (retain) CIImage *inputShift;

- (void).cxx_destruct;
- (id)centerShift;
- (id)customAttributes;
- (id)deltaShift;
- (id)init;
- (id)inputShift;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })outputExtent;
- (id)outputImage;
- (void)setCenterShift:(id)arg1;
- (void)setDeltaShift:(id)arg1;
- (void)setInputShift:(id)arg1;

@end
