/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleCVA.framework/AppleCVA
 */

@interface CVADepthFilter : CIFilter {
    CIImage * _inputAlpha;
    CIImage * _inputPrevShift;
    CIImage * _inputShift;
    CIImage * _shift;
    NSNumber * _shiftBlurRadius;
    NSNumber * _shiftFillValue;
    NSNumber * _shiftInFocus;
    NSNumber * _shiftUpdateRate;
}

@property (retain) CIImage *inputAlpha;
@property (retain) CIImage *inputPrevShift;
@property (retain) CIImage *inputShift;
@property (retain) CIImage *shift;
@property (retain) NSNumber *shiftBlurRadius;
@property (retain) NSNumber *shiftFillValue;
@property (retain) NSNumber *shiftInFocus;
@property (retain) NSNumber *shiftUpdateRate;

- (void).cxx_destruct;
- (id)customAttributes;
- (id)init;
- (id)inputAlpha;
- (id)inputPrevShift;
- (id)inputShift;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })outputExtent;
- (id)outputImage;
- (void)setInputAlpha:(id)arg1;
- (void)setInputPrevShift:(id)arg1;
- (void)setInputShift:(id)arg1;
- (void)setShift:(id)arg1;
- (void)setShiftBlurRadius:(id)arg1;
- (void)setShiftFillValue:(id)arg1;
- (void)setShiftInFocus:(id)arg1;
- (void)setShiftUpdateRate:(id)arg1;
- (id)shift;
- (id)shiftBlurRadius;
- (id)shiftFillValue;
- (id)shiftInFocus;
- (id)shiftUpdateRate;

@end
