/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleCVA.framework/AppleCVA
 */

@interface CVAFixupFilter : CIFilter {
    CIImage * _inputBlurred;
    CIImage * _inputImage;
}

@property (retain) CIImage *inputBlurred;
@property (retain) CIImage *inputImage;

- (void).cxx_destruct;
- (id)customAttributes;
- (id)init;
- (id)inputBlurred;
- (id)inputImage;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })outputExtent;
- (id)outputImage;
- (void)setInputBlurred:(id)arg1;
- (void)setInputImage:(id)arg1;

@end
