/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleCVA.framework/AppleCVA
 */

@interface CVAShallowDoFRenderer : NSObject {
    CVAAlphaFilter * _alphaFilter;
    CVABGFilter * _bgFilter;
    CVACoCFilter * _cocFilter;
    CIFilter * _compositingFilter;
    CIFilter * _cropFilter;
    CVADepthFilter * _depthFilter;
    CVAFGFilter * _fgFilter;
    CVAFixupFilter * _fixupFilter;
    CIFilter * _maskedVariableBlurFilter;
    CIImage * _prevShift;
    CVATriangleXFilter * _triangleXFilter;
    CVATriangleYFilter * _triangleYFilter;
}

@property (nonatomic, retain) CVAAlphaFilter *alphaFilter;
@property (nonatomic, retain) CVABGFilter *bgFilter;
@property (nonatomic, retain) CVACoCFilter *cocFilter;
@property (nonatomic, retain) CIFilter *compositingFilter;
@property (nonatomic, retain) CIFilter *cropFilter;
@property (nonatomic, retain) CVADepthFilter *depthFilter;
@property (nonatomic, retain) CVAFGFilter *fgFilter;
@property (nonatomic, retain) CVAFixupFilter *fixupFilter;
@property (nonatomic, retain) CIFilter *maskedVariableBlurFilter;
@property (retain) CIImage *prevShift;
@property (nonatomic, retain) CVATriangleXFilter *triangleXFilter;
@property (nonatomic, retain) CVATriangleYFilter *triangleYFilter;

- (void).cxx_destruct;
- (id)alphaFilter;
- (id)bgFilter;
- (id)cocFilter;
- (id)compositingFilter;
- (id)cropFilter;
- (id)depthFilter;
- (id)fgFilter;
- (id)fixupFilter;
- (float)getMaxCoCRadius:(float)arg1 withFocusAt:(float)arg2 withFNumber:(float)arg3 withXResolution:(float)arg4;
- (id)init;
- (id)maskedVariableBlurFilter;
- (id)prevShift;
- (id)render:(id)arg1 withAlpha:(id)arg2 withCoCRadius:(float)arg3;
- (id)render:(id)arg1 withAlpha:(id)arg2 withShift:(id)arg3 withPrevShift:(id)arg4 withShiftUpdateRate:(float)arg5 withShiftBlurRadius:(float)arg6 withShiftAtInf:(float)arg7 withShiftInFocus:(float)arg8 withShiftFillValue:(float)arg9 withFNumber:(float)arg10 withRenderedBuffer:(int)arg11;
- (id)renderTriangle:(id)arg1 withAlpha:(id)arg2;
- (void)setAlphaFilter:(id)arg1;
- (void)setBgFilter:(id)arg1;
- (void)setCocFilter:(id)arg1;
- (void)setCompositingFilter:(id)arg1;
- (void)setCropFilter:(id)arg1;
- (void)setDepthFilter:(id)arg1;
- (void)setFgFilter:(id)arg1;
- (void)setFixupFilter:(id)arg1;
- (void)setMaskedVariableBlurFilter:(id)arg1;
- (void)setPrevShift:(id)arg1;
- (void)setTriangleXFilter:(id)arg1;
- (void)setTriangleYFilter:(id)arg1;
- (id)triangleXFilter;
- (id)triangleYFilter;

@end
